### ISSUE TITLE
Package is unreleased, and thus unavailable in `roc-start` tool

### ISSUE THREAD

**Issue by imclerran** [shritesh/roc-image#2]
Package is not available in [roc-start](https://github.com/imclerran/roc-start) CLI tool.

I'd love to get your package listed in roc-start, but this requires a Github release, and a blake-3 hashed tarball. I've opened PR #1 to add the github workflow which will generate the tarball on release, so once that is merged, all that's required is to draft a release on Github.

Hope to get your package listed soon! 🚀

**Comment by shritesh** [comment]
Thank you for the PR. I've done a new release.

**Comment by imclerran** [comment]
You got it! And thank YOU! Just ran `roc-start update`, and your package is now showing up in the UI 😁
